jobs:
  build:
    needs:
    - check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Setup PostgreSQL SSL Permissions
      run: 'chmod 0400 ./driver/src/test/resources/certdir/server/server.key

        sudo chown 70:70 ./driver/src/test/resources/certdir/server/server.key

        '
    - continue-on-error: true
      name: Build & Test
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: test -x checkstyleMain -x checkstyleTest
        job-id: jdk${{ matrix.jdk }}-build-test
        properties: 'postgresVersions=${{ matrix.pg }}

          '
    strategy:
      matrix:
        jdk:
        - 8
        - 11
        pg:
        - 10
        - 11
        - 12
        - 13
  check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Run Checks
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: checkstyleMain checkstyleTest
        job-id: jdk11-build-test
  deploy:
    if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/rel/v')
    needs:
    - check
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Publish Maven Artifacts
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: publish
        job-id: jdk11-build-test
        properties: 'postgresVersions=12

          ossrhUsername=${{ secrets.OSSRH_USERNAME }}

          ossrhPassword=${{ secrets.OSSRH_PASSWORD }}

          '
    - continue-on-error: true
      env:
        GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        GRGIT_USER: kdubb
      name: Publish Documentation
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: documentation:gitPublishPush
        job-id: jdk11-build-test
        properties: 'postgresVersions=12

          docsRepoUri=https://github.com/impossibl/pgjdbc-ng.git

          '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
